#!/bin/bash

#使用gdb进行gg的调试

curPwd=$(pwd)
curPwd="$curPwd""/gg"

info=($(ps aux|grep $curPwd |awk '{print $2 "\t" $11}'))

if [ ${info[1]} == $curPwd ]
then
    gdb attach ${info[0]}
else
    ./start.sh
    if [ $? != 0 ]
    then
        echo "===只能在server目录使用==="
        exit
    fi
    $0
fi
